@ApiIngesta_HostAddress = https://localhost:7036

POST {{ApiIngesta_HostAddress}}/api/infracciones
Content-Type: application/json

{
  "placa": "MBC1234",
  "velocidad": 95,
  "limiteVelocidad": 50,
  "fechaDeteccion": "2026-07-19T20:00:00Z"
}

###