// <auto-generated />
using System;
using ApiIngesta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiIngesta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719184125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiIngesta.Models.Infraccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LimiteVelocidad")
                        .HasColumnType("numeric");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Velocidad")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Infracciones");
                });

            modelBuilder.Entity("ApiIngesta.Models.MensajePendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MensajesPendientes");
                });
#pragma warning restore 612, 618
        }
    }
}
